import type {
  CatalogItem,
  Client,
  Employee,
  FiscalDocument,
  GeneratedDocument,
  Service,
  ServiceType,
} from "@/lib/types";

const now = new Date();
const isoDaysAgo = (days: number) =>
  new Date(now.getTime() - days * 86400000).toISOString();
const isoDaysAhead = (days: number) =>
  new Date(now.getTime() + days * 86400000).toISOString();

export const demoClients: Client[] = [
  {
    id: "client-1",
    name: "Condomínio Jardim Imperial",
    person_type: "PJ",
    document: "12.345.678/0001-90",
    phone: "(11) 98765-4321",
    email: "sindico@jardimimperial.com.br",
    notes: "Contato preferencial por WhatsApp.",
    active: true,
    created_at: isoDaysAgo(70),
    client_addresses: [
      {
        id: "address-1",
        client_id: "client-1",
        label: "Portaria principal",
        street: "Rua das Palmeiras",
        number: "420",
        complement: null,
        district: "Jardim Imperial",
        city: "São Paulo",
        state: "SP",
        postal_code: "01234-000",
        is_primary: true,
      },
    ],
  },
  {
    id: "client-2",
    name: "Mariana Oliveira",
    person_type: "PF",
    document: "123.456.789-00",
    phone: "(11) 97654-3210",
    email: "mariana@email.com",
    notes: null,
    active: true,
    created_at: isoDaysAgo(38),
  },
  {
    id: "client-3",
    name: "Mercado Santa Clara",
    person_type: "PJ",
    document: "98.765.432/0001-10",
    phone: "(11) 3456-7890",
    email: "financeiro@santaclara.com.br",
    notes: "Enviar proposta também para o financeiro.",
    active: true,
    created_at: isoDaysAgo(24),
  },
];

export const demoEmployees: Employee[] = [
  {
    id: "employee-1",
    name: "Carlos Mendes",
    document: "111.222.333-44",
    phone: "(11) 98888-1122",
    daily_rate: 280,
    half_daily_rate: 160,
    default_bonus: 100,
    active: true,
    notes: "Especialista em CFTV.",
    created_at: isoDaysAgo(120),
  },
  {
    id: "employee-2",
    name: "Rafael Santos",
    document: "555.666.777-88",
    phone: "(11) 97777-3344",
    daily_rate: 240,
    half_daily_rate: 140,
    default_bonus: 80,
    active: true,
    notes: "Instalação elétrica e cabeamento.",
    created_at: isoDaysAgo(98),
  },
  {
    id: "employee-3",
    name: "João Lima",
    document: "999.000.111-22",
    phone: "(11) 96666-5566",
    daily_rate: 220,
    half_daily_rate: 130,
    default_bonus: 70,
    active: true,
    notes: null,
    created_at: isoDaysAgo(72),
  },
];

export const demoServiceTypes: ServiceType[] = [
  {
    id: "type-1",
    name: "Instalação de CFTV",
    description: "Câmeras, DVR/NVR e configuração de acesso.",
    active: true,
  },
  {
    id: "type-2",
    name: "Cabeamento estruturado",
    description: "Passagem, organização e certificação de cabos.",
    active: true,
  },
  {
    id: "type-3",
    name: "Manutenção",
    description: "Diagnóstico e correção em instalações existentes.",
    active: true,
  },
];

export const demoCatalogItems: CatalogItem[] = [
  {
    id: "item-1",
    name: "Ponto de câmera instalado",
    unit: "un",
    sale_price: 850,
    standard_cost: 520,
    active: true,
  },
  {
    id: "item-2",
    name: "Ponto de rede CAT6",
    unit: "un",
    sale_price: 290,
    standard_cost: 150,
    active: true,
  },
  {
    id: "item-3",
    name: "Diária técnica",
    unit: "dia",
    sale_price: 650,
    standard_cost: 280,
    active: true,
  },
];

export const demoServices: Service[] = [
  {
    id: "service-1",
    title: "Modernização das câmeras da portaria",
    client_id: "client-1",
    client_address_id: "address-1",
    service_type_id: "type-1",
    description:
      "Substituição de 8 câmeras e configuração do acesso remoto para o síndico.",
    customer_notes: "Proposta válida por 15 dias.",
    internal_notes: "Confirmar disponibilidade do elevador de serviço.",
    status: "EM_EXECUCAO",
    sale_amount: 12800,
    estimated_cost_amount: 6700,
    estimated_start_at: isoDaysAgo(3),
    estimated_end_at: isoDaysAhead(2),
    actual_start_at: isoDaysAgo(3),
    actual_end_at: null,
    warranty_until: null,
    created_at: isoDaysAgo(18),
    updated_at: isoDaysAgo(1),
    clients: demoClients[0],
    service_types: demoServiceTypes[0],
    service_costs: [
      {
        id: "cost-1",
        service_id: "service-1",
        employee_id: null,
        category: "COMBUSTIVEL",
        description: "Abastecimento da ida",
        amount: 190,
        cost_date: isoDaysAgo(3).slice(0, 10),
        visible_to_customer: false,
        created_at: isoDaysAgo(3),
      },
      {
        id: "cost-2",
        service_id: "service-1",
        employee_id: null,
        category: "ALMOCO",
        description: "Equipe de 3 pessoas",
        amount: 156,
        cost_date: isoDaysAgo(2).slice(0, 10),
        visible_to_customer: false,
        created_at: isoDaysAgo(2),
      },
    ],
    service_items: [
      {
        id: "service-item-1",
        service_id: "service-1",
        description: "Câmera IP 4MP instalada",
        unit: "un",
        quantity: 8,
        unit_price: 1250,
        unit_cost: 690,
        total_price: 10000,
      },
      {
        id: "service-item-2",
        service_id: "service-1",
        description: "Configuração e treinamento",
        unit: "serviço",
        quantity: 1,
        unit_price: 2800,
        unit_cost: 1180,
        total_price: 2800,
      },
    ],
    service_employees: [
      {
        id: "assignment-1",
        service_id: "service-1",
        employee_id: "employee-1",
        daily_rate_snapshot: 280,
        half_daily_rate_snapshot: 160,
        bonus_snapshot: 100,
        days_worked: 2,
        half_days_worked: 0,
        bonus_paid: 0,
        employees: demoEmployees[0],
      },
      {
        id: "assignment-2",
        service_id: "service-1",
        employee_id: "employee-2",
        daily_rate_snapshot: 240,
        half_daily_rate_snapshot: 140,
        bonus_snapshot: 80,
        days_worked: 2,
        half_days_worked: 0,
        bonus_paid: 0,
        employees: demoEmployees[1],
      },
    ],
  },
  {
    id: "service-2",
    title: "Rede e Wi-Fi do novo escritório",
    client_id: "client-3",
    client_address_id: null,
    service_type_id: "type-2",
    description: "Instalação de 18 pontos CAT6 e dois access points.",
    customer_notes: null,
    internal_notes: "Aguardar planta atualizada.",
    status: "ORCAMENTO",
    sale_amount: 9450,
    estimated_cost_amount: 4800,
    estimated_start_at: isoDaysAhead(8),
    estimated_end_at: isoDaysAhead(11),
    actual_start_at: null,
    actual_end_at: null,
    warranty_until: null,
    created_at: isoDaysAgo(4),
    updated_at: isoDaysAgo(2),
    clients: demoClients[2],
    service_types: demoServiceTypes[1],
    service_costs: [],
    service_items: [],
    service_employees: [],
  },
  {
    id: "service-3",
    title: "Ajuste no interfone e fechadura",
    client_id: "client-2",
    client_address_id: null,
    service_type_id: "type-3",
    description: "Revisão completa após oscilação de energia.",
    customer_notes: null,
    internal_notes: null,
    status: "GARANTIA",
    sale_amount: 2200,
    estimated_cost_amount: 900,
    estimated_start_at: isoDaysAgo(28),
    estimated_end_at: isoDaysAgo(27),
    actual_start_at: isoDaysAgo(28),
    actual_end_at: isoDaysAgo(27),
    warranty_until: isoDaysAhead(62).slice(0, 10),
    created_at: isoDaysAgo(33),
    updated_at: isoDaysAgo(6),
    clients: demoClients[1],
    service_types: demoServiceTypes[2],
    service_costs: [
      {
        id: "cost-3",
        service_id: "service-3",
        employee_id: null,
        category: "MATERIAL_EXTRA",
        description: "Fonte de alimentação",
        amount: 215,
        cost_date: isoDaysAgo(28).slice(0, 10),
        visible_to_customer: false,
        created_at: isoDaysAgo(28),
      },
    ],
    service_items: [],
    service_employees: [],
  },
  {
    id: "service-4",
    title: "Câmeras do depósito",
    client_id: "client-3",
    client_address_id: null,
    service_type_id: "type-1",
    description: "Projeto concluído com 12 câmeras.",
    customer_notes: null,
    internal_notes: null,
    status: "FINALIZADO",
    sale_amount: 18500,
    estimated_cost_amount: 9800,
    estimated_start_at: isoDaysAgo(54),
    estimated_end_at: isoDaysAgo(49),
    actual_start_at: isoDaysAgo(54),
    actual_end_at: isoDaysAgo(48),
    warranty_until: isoDaysAgo(2).slice(0, 10),
    created_at: isoDaysAgo(65),
    updated_at: isoDaysAgo(48),
    clients: demoClients[2],
    service_types: demoServiceTypes[0],
    service_costs: [
      {
        id: "cost-4",
        service_id: "service-4",
        employee_id: null,
        category: "OUTROS",
        description: "Custos consolidados",
        amount: 9240,
        cost_date: isoDaysAgo(48).slice(0, 10),
        visible_to_customer: false,
        created_at: isoDaysAgo(48),
      },
    ],
    service_items: [],
    service_employees: [],
  },
];

export const demoFiscalDocuments: FiscalDocument[] = [
  {
    id: "fiscal-1",
    service_id: "service-4",
    document_type: "NFSE",
    status: "EMITIDA",
    amount: 18500,
    customer_name: demoClients[2].name,
    fiscal_description: "Instalação e configuração de sistema de CFTV.",
    number: "1042",
    series: "A",
    access_key: null,
    consultation_url: null,
    notes: "Emitida pela contabilidade.",
    created_at: isoDaysAgo(47),
    services: {
      id: "service-4",
      title: "Câmeras do depósito",
      clients: demoClients[2],
    },
  },
  {
    id: "fiscal-2",
    service_id: "service-1",
    document_type: "NFSE",
    status: "AGUARDANDO_CONTABILIDADE",
    amount: 12800,
    customer_name: demoClients[0].name,
    fiscal_description: "Modernização do sistema de monitoramento.",
    number: null,
    series: null,
    access_key: null,
    consultation_url: null,
    notes: "Confirmar código municipal do serviço.",
    created_at: isoDaysAgo(2),
    services: {
      id: "service-1",
      title: "Modernização das câmeras da portaria",
      clients: demoClients[0],
    },
  },
];

export const demoDocuments: GeneratedDocument[] = [
  {
    id: "document-1",
    service_id: "service-1",
    name: "orcamento-modernizacao-portaria.docx",
    storage_path: "demo/orcamento-modernizacao-portaria.docx",
    created_at: isoDaysAgo(17),
    services: {
      id: "service-1",
      title: "Modernização das câmeras da portaria",
    },
  },
  {
    id: "document-2",
    service_id: "service-2",
    name: "orcamento-rede-escritorio.docx",
    storage_path: "demo/orcamento-rede-escritorio.docx",
    created_at: isoDaysAgo(3),
    services: {
      id: "service-2",
      title: "Rede e Wi-Fi do novo escritório",
    },
  },
];
